services:
  - type: web
    name: opticwise-frontend
    runtime: node
    region: oregon
    plan: starter
    branch: main
    buildCommand: cd ow && npm install && npx prisma generate && npm run build
    startCommand: cd ow && npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://opticwise_db_user:er6uVwAIHfgoiGZ1u2IUdlayvZ0ouRJo@dpg-d4eboeh5pdvs73fpagfg-a.oregon-postgres.render.com/opticwise_db
      - key: AUTH_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_BASE_URL
        value: https://opticwise-frontend.onrender.com
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
